/*
 * FILE: SVGWriterPostProcessor.java
 * DATE OF CREATION: Fri Oct 15 13:47:33 2004
 * MODIF: Fri Oct 15 13:56:42 2004 by Emmanuel Pietriga (emmanuel.pietriga@inria.fr)
 * Copyright (c) INRIA, 2004-2010. All Rights Reserved
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * For full terms see the file COPYING.
 *
 * $Id: SVGWriterPostProcessor.java 3747 2010-08-29 11:23:53Z epietrig $
 */
package fr.inria.zvtm.svg;

import fr.inria.zvtm.glyphs.Glyph;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

/**
 * SVGWriter Post Processing interface. To manipulate DOM elements generated by an SVGWriter before serialization.
 *
 * @author Emmanuel Pietriga
 */
public interface SVGWriterPostProcessor {

    /**
     * Called each time a new SVG element is created by the SVGWriter.
     *
     * @param el the XML/SVG element created for Glyph gl
     * @param gl the Glyph associated with the element created
     * @param d  the Document element el belongs to
     */
    public void newElementCreated(Element el, Glyph gl, Document d);

}
